version: "3.7"

services:
  backend:
    container_name: backend
    image: denniska/besuchernachweis-backend
    environment:
        DATENBANKPFAD: /app/data/Besuchernachweis.db
        TOKENLIFETIME: 12
        APPSECRET: AppSecret123
        LOGINVERSUCHE: 5
    ports:
        - 80:80
    restart: unless-stopped
    volumes:
        - ./database:/app/data/